

Vienuoliai, kad ir kiltų vienuoliui neužsiimančiam [proto] vystymu {meditacija} toks noras: "O, kad mano protas išsilaisvintų  dėl neprisirišimo nuo intakų!" Jo protas neišsilaisvintų dėl neprisirišimo nuo intakų. Kodėl taip yra? Pasakytina, dėl [proto] neišvystymo. Ko neišvystymo? <a href="http://theravada.lt/vertimai/satipatthanasuttam-p1">Keturių atidumo įsteigimų</a>, <a href="http://theravada.lt/vertimai/pacinasuttam">keturių teisingų stengimųsi</a>, keturių antžmogiškų galių pagrindų, <a href="http://theravada.lt/vertimai/dutiyavibhangasutta%E1%B9%83">penkių valdančių gebėjimų</a>, penkių stiprybių, <a href="http://theravada.lt/vertimai/himavantasuttam-himalaju">septynių atbudimo veiksnių</a>, <a href="http://theravada.lt/vertimai/SN-V-I-i-8-vibhangasuttam">tauriojo aštuonialypio kelio</a>.

Sakykime, vienuoliai, [būtų] aštuoni, dešimt ar dvylika vištos kiaušinių. Višta ant jų nei tinkamai tupėtų, nei tinkamai perėtų, nei tinkamai brandintų jų. Kad ir kiltų tai vištai toks noras: "O kad mano viščiukai, nagų ar snapų galiukais prakalę kiaušinio lukštus saugiai išsiristų!" Neįmanoma, kad tie viščiukai nagų ar snapų galiukais prakalę kiaušinio lukštus saugiai išsiristų. Kodėl taip yra? Dėl to, kad, vienuoliai, višta ant kiaušinių nei tinkamai tupėjo, nei tinkamai perėjo, nei tinkamai brandino juos. Lygiai taip pat, vienuoliai, kad ir kiltų vienuoliui neužsiimančiam [proto] vystymu {meditacija} toks noras: “O, kad mano protas išsilaisvintų  dėl neprisirišimo nuo intakų!” Jo protas neišsilaisvintų dėl neprisirišimo nuo intakų. Kodėl taip yra? Pasakytina, dėl [proto] neišvystymo. Ko neišvystymo? Keturių atidumo įsteigimų, keturių teisingų stengimųsi, keturių antžmogiškų galių pagrindų, penkių valdančių gebėjimų, penkių stiprybių,septynių atbudimo veiksnių, tauriojo aštuonialypio kelio.

Vienuoliai, kad ir nekiltų vienuoliui užsiimančiam [proto] vystymu {meditacija} toks noras: "O, kad mano protas išsilaisvintų dėl neprisirišimo nuo intakų!" Vis vien jo protas išsilaisvintų dėl neprisirišimo nuo intakų. Kodėl taip yra? Pasakytina, dėl [proto] išvystymo. Ko išvystymo? Keturių atidumo įsteigimų, keturių teisingų stengimųsi, keturių antžmogiškų galių pagrindų, penkių valdančių gebėjimų, penkių stiprybių,  septynių atbudimo veiksnių, tauriojo aštuonialypio kelio.

Sakykime, vienuoliai, [būtų] aštuoni, dešimt ar dvylika vištos kiaušinių. Višta ant jų tinkamai tupėtų, tinkamai perėtų, tinkamai brandintų juos. Kad ir nekiltų tai vištai toks noras: "O kad mano viščiukai, nagų ar snapų galiukais prakalę kiaušinio lukštus saugiai išsiristų!" Vis vien įmanoma, kad tie viščiukai nagų ar snapų galiukais prakalę kiaušinio lukštus saugiai išsiris. Kodėl taip yra? Dėl to, kad, vienuoliai, višta ant kiaušinių tinkamai tupėjo, tinkamai perėjo, tinkamai brandino juos. Lygiai taip pat, vienuoliai, kad ir nekiltų vienuoliui užsiimančiam [proto] vystymu {meditacija} toks noras: “O, kad mano protas išsilaisvintų  dėl neprisirišimo nuo intakų!” Vis vien jo protas išsilaisvintų dėl neprisirišimo nuo intakų. Kodėl taip yra? Pasakytina, dėl [proto] išvystymo. Ko išvystymo? Keturių atidumo įsteigimų… tauriojo aštuonialypio kelio.

Sakykime, vienuoliai, dailidė ar dailidės padėjėjas žiūrėdamas į kirvio rankeną pamatytų pirštų ir nykščio žymes. Betgi jis nežinotų: "Štai tiek kirvio rankena susidėvėjo šiandien, štai tiek vakar, štai tiek prieš tai". Bet kai ji susidėvi, jis žino, kad ji susidėvėjo. Lygiai gi taip pat, vienuoliai, vienuolis užsiimantis [proto] vystymu {meditacija} nežino: “Štai tiek teršalų išnyko šiandien, štai tiek vakar, štai tiek prieš tai”. Bet kai jie išnyksta, jis žino, kad jie išnyko.

Sakykime, vienuoliai būtų vandenyno laivas su lynais švartavimui. Po šešių mėnesių buvimo vandenyje, kai jis žiemą pastatytas krante, veikiami vėjo ir saulės lynai, permerkti lietaus iš lietaus debesies, nesunkiai suirs, taps supuvę. Lygiai taip pat, vienuoliai, vienuolio užsiimančio [proto] vystymu {meditacija} saitai nesunkiai atsileidžia, tampa supuvę.

**Vystymas (Bhāvanāsuttaṃ, AN 7.7.7)**

**‘‘Bhāvanaṃ ananuyuttassa, bhikkhave, bhikkhuno viharato** Vienuoliai, vienuoliui neužsiimančiam [proto] vystymu {meditacija} **kiñcāpi evaṃ icchā uppajjeyya –** kad ir kiltų toks noras: **‘aho vata me anupādāya āsavehi cittaṃ vimucceyyā’ti,** "O, kad mano protas išsilaisvintų dėl neprisirišimo nuo intakų!" **atha khvassa neva anupādāya āsavehi cittaṃ vimuccati.** Jo protas tuomet neišsilaisvintų dėl neprisirišimo nuo intakų. **Taṃ kissa hetu?** Kodėl taip yra? **‘Abhāvitattā’tissa vacanīyaṃ.** Pasakytina, dėl [proto] neišvystymo. **Kissa abhāvitattā?** Ko neišvystymo? **Catunnaṃ satipaṭṭhānānaṃ,** Keturių atidumo įsteigimų, **catunnaṃ sammappadhānānaṃ,** keturių teisingų stengimųsi, **catunnaṃ iddhipādānaṃ,** keturių antžmogiškų galių pagrindų, **pañcannaṃ indriyānaṃ,** penkių valdančių gebėjimų, **pañcannaṃ balānaṃ,** penkių stiprybių, **sattannaṃ bojjhaṅgānaṃ,** septynių atbudimo veiksnių, **ariyassa aṭṭhaṅgikassa maggassa.** tauriojo aštuonialypio kelio.

**‘‘Seyyathāpi, bhikkhave,** Sakykime, vienuoliai, **kukkuṭiyā aṇḍāni aṭṭha vā dasa vā dvādasa vā.** [būtų] aštuoni, dešimt ar dvylika vištos kiaušinių. **Tānassu kukkuṭiyā** Višta ant jų **na sammā adhisayitāni,** nei tinkamai tupėtų, **na sammā pariseditāni,** nei tinkamai perėtų, **na sammā paribhāvitāni.** nei tinkamai brandintų juos. **kiñcāpi tassā kukkuṭiyā evaṃ icchā uppajjeyya –** Kad ir kiltų tai vištai toks noras: **‘aho vata me kukkuṭapotakā** "O kad mano viščiukai, **pādanakhasikhāya vā mukhatuṇḍakena vā** nagų ar snapų galiukais **aṇḍakosaṃ padāletvā** prakalę kiaušinio lukštus **sotthinā abhinibbhijjeyyu’nti,** saugiai išsiristų!" **atha kho abhabbāva**  Neįmanoma, kad **te kukkuṭapotakā** tie viščiukai **pādanakhasikhāya vā mukhatuṇḍakena vā** nagų ar snapų galiukais **aṇḍakosaṃ padāletvā** prakalę kiaušinio lukštus **sotthinā abhinibbhijjituṃ.** saugiai išsiristų. **Taṃ kissa hetu?** Kodėl taip yra? **Tathā hi, bhikkhave,** Dėl to, kad, vienuoliai, **kukkuṭiyā aṇḍāni** višta ant kiaušinių **na sammā adhisayitāni,** nei tinkamai tupėjo, **na sammā pariseditāni,** nei tinkamai perėjo, **na sammā paribhāvitāni.** nei tinkamai brandino. **Evamevaṃ kho, bhikkhave,** Lygiai taip pat, vienuoliai, **bhāvanaṃ ananuyuttassa bhikkhuno viharato** vienuoliui neužsiimančiam [proto] vystymu {meditacija} **kiñcāpi evaṃ icchā uppajjeyya –** kad ir kiltų toks noras: **‘aho vata me anupādāya āsavehi cittaṃ vimucceyyā’ti,** “O, kad mano protas išsilaisvintų  dėl neprisirišimo nuo intakų!” **atha khvassa neva anupādāya āsavehi cittaṃ vimuccati.** Jo protas neišsilaisvintų dėl neprisirišimo nuo intakų. **Taṃ kissa hetu?** Kodėl taip yra? **‘Abhāvitattā’tissa vacanīyaṃ.** Pasakytina, dėl [proto] neišvystymo. **Kissa abhāvitattā?** Ko neišvystymo? **Catunnaṃ satipaṭṭhānānaṃ,** Keturių atidumo įsteigimų, **catunnaṃ sammappadhānānaṃ,** keturių teisingų stengimųsi, **catunnaṃ iddhipādānaṃ,** keturių antžmogiškų galių pagrindų, **pañcannaṃ indriyānaṃ,** penkių valdančių gebėjimų, **pañcannaṃ balānaṃ,** penkių stiprybių, **sattannaṃ bojjhaṅgānaṃ,** septynių atbudimo veiksnių, **ariyassa aṭṭhaṅgikassa maggassa.** tauriojo aštuonialypio kelio.

**‘‘Bhāvanaṃ anuyuttassa, bhikkhave, bhikkhuno viharato** Vienuoliai, vienuoliui užsiimančiam [proto] vystymu {meditacija} **kiñcāpi na evaṃ icchā uppajjeyya –** kad ir nekiltų toks noras: **‘aho vata me anupādāya āsavehi cittaṃ vimucceyyā’ti,** "O, kad mano protas išsilaisvintų dėl neprisirišimo nuo intakų!" **atha khvassa anupādāya āsavehi cittaṃ vimuccati.** Vis vien jo protas išsilaisvintų dėl neprisirišimo nuo intakų. **Taṃ kissa hetu?** Kodėl taip yra? **‘Bhāvitattā’tissa vacanīyaṃ.** Pasakytina, dėl [proto] išvystymo. **Kissa bhāvitattā?** Ko išvystymo? **Catunnaṃ satipaṭṭhānānaṃ,** Keturių atidumo įsteigimų, **catunnaṃ sammappadhānānaṃ,** keturių teisingų stengimųsi, **catunnaṃ iddhipādānaṃ,** keturių antžmogiškų galių pagrindų, **pañcannaṃ indriyānaṃ,** penkių valdančių gebėjimų, **pañcannaṃ balānaṃ,** penkių stiprybių, **sattannaṃ bojjhaṅgānaṃ,** septynių atbudimo veiksnių, **ariyassa aṭṭhaṅgikassa maggassa.** tauriojo aštuonialypio kelio.

**‘‘Seyyathāpi, bhikkhave,** Sakykime, vienuoliai, **kukkuṭiyā aṇḍāni aṭṭha vā dasa vā dvādasa vā.** [būtų] aštuoni, dešimt ar dvylika vištos kiaušinių. **Tānassu kukkuṭiyā** Višta ant jų **sammā adhisayitāni,** tinkamai tupėtų, **sammā pariseditāni,** tinkamai perėtų, **sammā paribhāvitāni.** tinkamai brandintų. **Kiñcāpi tassā kukkuṭiyā evaṃ icchā uppajjeyya –** Kad ir nekiltų tai vištai toks noras: **‘aho vata me kukkuṭapotakā** "O kad mano viščiukai, **pādanakhasikhāya vā mukhatuṇḍakena vā** nagų ar snapų galiukais **aṇḍakosaṃ padāletvā** prakalę kiaušinio lukštus **sotthinā abhinibbhijjeyyu’nti,** saugiai išsiristų!" **atha kho abhabbāva** Įmanoma, kad **te kukkuṭapotakā** tie viščiukai **pādanakhasikhāya vā mukhatuṇḍakena vā** nagų ar snapų galiukais **aṇḍakosaṃ padāletvā** prakalę kiaušinio lukštus **sotthinā abhinibbhijjituṃ.** saugiai išsiris. **Taṃ kissa hetu?** Kodėl taip yra? **Tathā hi, bhikkhave,** Dėl to, kad, vienuoliai, **kukkuṭiyā aṇḍāni** višta ant kiaušinių **sammā adhisayitāni,** tinkamai tupėjo, **sammā pariseditāni,** tinkamai perėjo, **sammā paribhāvitāni.** tinkamai brandino. **Evamevaṃ kho, bhikkhave,** Lygiai taip pat, vienuoliai, **bhāvanaṃ anuyuttassa bhikkhuno viharato** vienuoliui užsiimančiam [proto] vystymu {meditacija} **kiñcāpi na evaṃ icchā uppajjeyya –** kad ir nekiltų toks noras: **‘aho vata me anupādāya āsavehi cittaṃ vimucceyyā’ti,** “O, kad mano protas išsilaisvintų  dėl neprisirišimo nuo intakų!” **atha khvassa anupādāya āsavehi cittaṃ vimuccati.** Vis vien jo protas išsilaisvintų dėl neprisirišimo nuo intakų. **Taṃ kissa hetu?** Kodėl taip yra? **‘Bhāvitattā’tissa vacanīyaṃ.** Pasakytina, dėl [proto] išvystymo. **Kissa bhāvitattā?** Ko išvystymo? **Catunnaṃ satipaṭṭhānānaṃ...pe...** Keturių atidumo įsteigimų... **ariyassa aṭṭhaṅgikassa maggassa.** tauriojo aštuonialypio kelio.

**‘‘Seyyathāpi, bhikkhave, phalagaṇḍassa [palagaṇḍassa (?)] vā phalagaṇḍantevāsikassa vā** Sakykime, vienuoliai, dailidė ar dailidės padėjėjas **dissanteva [khīyante (ka.)] vāsijaṭe [dissanti aṅgulipadāni (sī.), aṅgulapadāni dissanti aṅgulapadaṃ (ka.)]** žiūrėdamas į kirvio rankeną **aṅgulipadāni dissati [dissanti (syā.)] aṅguṭṭhapadaṃ [dissanti aṅgulipadāni (sī.), aṅgulapadāni dissanti aṅgulapadaṃ (ka.)].** pamatytų pirštų ir nykščio žymes. **No ca khvassa evaṃ ñāṇaṃ hoti –** Betgi jis nežinotų: **‘ettakaṃ me ajja vāsijaṭassa khīṇaṃ,** "Štai tiek kirvio rankena susidėvėjo šiandien, **ettakaṃ hiyyo,** štai tiek vakar, **ettakaṃ pare’ti,** štai tiek prieš tai". **atha khvassa khīṇe ‘khīṇa’nteva ñāṇaṃ hoti.** Bet kai ji susidėvi, jis žino, kad ji susidėvėjo.  **Evamevaṃ kho, bhikkhave,** Lygiai taip pat, vienuoliai, **bhāvanaṃ anuyuttassa bhikkhuno viharato kiñcāpi** vienuolis užsiimantis [proto] vystymu {meditacija} **na evaṃ ñāṇaṃ hoti –** nežino: **‘ettakaṃ me ajja āsavānaṃ khīṇaṃ,** “Štai tiek teršalų išnyko šiandien, **ettakaṃ hiyyo,** štai tiek vakar, **ettakaṃ pare’ti,** štai tiek prieš tai”. **atha khvassa khīṇe ‘khīṇa’nteva ñāṇaṃ hoti.** Bet kai jie išnyksta, jis žino, kad jie išnyko.

**‘‘Seyyathāpi, bhikkhave,** Sakykime, vienuoliai **sāmuddikāya nāvāya vettabandhanabaddhāya [vettabandhāya (ka.)]** vandenyne būtų laivas su lynais švartavimui. **cha māsāni udake pariyādāya** Po šešių mėnesių buvimo vandenyje, **hemantikena thale ukkhittāya** kai jis žiemą pastatytas krante, **vātātapaparetāni bandhanāni,** veikiami vėjo ir saulės lynai, **tni pāvussakena meghena abhippavuṭṭhāni** permerkti lietaus iš lietaus debesies **appakasireneva parihāyanti [paṭippassambhanti (sī. syā.)],** nesunkiai suirs, **pūtikāni bhavanti.** taps supuvę.  **Evamevaṃ kho, bhikkhave,** Lygiai gi taip pat, vienuoliai, **bhāvanaṃ anuyuttassa bhikkhuno viharato** vienuolio užsiimančio [proto] vystymu {meditacija} **appakasireneva saṃyojanāni paṭippassambhanti,** saitai nesunkiai atsileidžia **pūtikāni bhavantī’’ti.** tampa supuvę.
